### ISSUE TITLE
aanpassingen functies KRWtrends

### ISSUE THREAD

**Issue by NJSchoffelen** [rivm-syso/KRWTrends#7]
Hoi Mike,

Om voor ons het pakket te laten draaien hebben wij de volgende aanpassingen gemaakt aan een aantal functies in het pakket. Hier onze omschrijvingen.

`##############################################################################################################################
##############################################################################################################################

# dw: we hebben een eigen tabel drempelwaarden gemaakt en willen die tabel gebruiken, in plaats van de tabel data(drempelwaarden)
# In onze eigen tabel staat namelijk een combinatie van bepaalde grondwaterlichamen. Anders loopt het script verderop weer vast

dw2 = function (param, gwl) 
{
  x <- subset(drempelwaarden, select = param, gwbident == gwl)[[param]]
  if (length(x) == 0) {
    warning("dw: no value found")
    x <- NA
  }
  return(x)
}

# mktrends: toegevoegd dat de functie aangeeft wanneer er te weinig metingen zijn voor de analyse (kan wellicht ook in warning-vorm
# in plaats van als string)

mktrends2 = function (i, x, trim = FALSE, trimfactor = 1.5, dw.plot = TRUE, 
                      psig = 0.05, alter = "two.sided", rpDL = TRUE, make.plot = FALSE,replacefactor = 0.5) 
{
  dw <- x$norm[1]
  param <- x$parameter[1]
  d <- x %>% select(putfilter, meetjaar, waarde, detectielimiet, 
                    eenheid) %>% mutate(jr = meetjaar - min(meetjaar)) %>% 
    arrange(jr) %>% filter(putfilter == i)
  d <- na.omit(d)
  if (rpDL) {
    d <- d %>% replaceDL(replaceval = replacefactor)
  }
  if (nrow(d) < 5) {
    return(print(paste("Meetreeks kleiner dan 5 metingen"))) # i,param,
  }
  if (nrow(d[d$detectielimiet < 1, ]) < 4) {
    return(print(paste("Minder dan 4 metingen boven detectie"))) # i,param,
  }
  if (trim) {
    d <- mutate(d, waarde = rmoutlier(d[["Waarde"]], 
                                      factor = trimfactor, na.rm = TRUE))
  }
  d <- na.omit(d)
  n <- nrow(d)
  d.mk <- EnvStats::kendallTrendTest(waarde ~ jr, data = d, 
                                     alternative = alter)
  res <- data.frame(putfilter = i, S = d.mk$S, var = d.mk$var.S, 
                    n = n, p = d.mk$p.value, tau = d.mk$estimate[1], slope = d.mk$estimate[2], 
                    intercept = d.mk$estimate[3], slopeLCL = d.mk$interval$limits[1], 
                    slopeUCL = d.mk$interval$limits[2], trend = (ifelse(d.mk$p.value <= 
                                                                          psig, "trend", "geen trend")), direction = (ifelse(d.mk$S <= 
                                                                                                                               0, "neerwaarts", "opwaarts")), stringsAsFactors = FALSE, 
                    row.names = i)
  if (make.plot) {
    d <- d %>% mutate(detectielimiet = ifelse(detectielimiet == 
                                                1, "< RG", "waarneming"))
    p <- ggplot(d, aes(jr, waarde, colour = detectielimiet))
    p <- p + geom_line(colour = "grey")
    p <- p + geom_point()
    if (dw.plot) {
      p <- p + geom_hline(aes(yintercept = dw, linetype = "drempelwaarde"), 
                          colour = "red")
      p <- p + geom_hline(aes(yintercept = 0.75 * dw, linetype = "75% drempelwaarde"), 
                          colour = "orange")
    }
    p <- p + theme(legend.position = "none", axis.text.x = element_text(angle = 90, 
                                                                        hjust = 1))
    p <- p + scale_x_continuous(breaks = d$jr, labels = d$meetjaar)
    p <- p + labs(x = "Jaar", y = paste("Concentratie", 
                                        param, strsplit(x$eenheid[1], " ")[[1]][1]), 
                  title = paste("Trend in filter", i))
    p <- p + theme(plot.title = element_text(hjust = 0.5), 
                   legend.position = "bottom")
    p <- p + scale_color_manual(name = "", values = c(`< RG` = "red", 
                                                      waarneming = "black"))
    p <- p + scale_linetype_manual(name = "", values = c(2, 
                                                         2), guide = guide_legend(override.aes = list(color = c("orange", 
                                                                                                                "red"))))
    if (res$p <= psig) {
      p <- p + geom_abline(intercept = res$intercept, slope = res$slope, 
                           color = "red")
    }
    return(p)
  }
  else {
    return(res)
  }
}

# toetsnormoverschrijding: testSerie(d) eruit gehaald omdat deze foutmeldingen geeft (functie bestaat niet)

toetsNormoverschrijding2 = function (d, toetsnorm = 0.75) 
{
  # testSerie(d)
  param <- d$parameter[1]
  n.tot <- nrow(d)
  d %>% filter(detectielimiet == 0) %>% mutate(dwratio = waarde/norm) %>% 
    filter(dwratio > toetsnorm) %>% summarise(n = n(), percentage = round(n()/n.tot * 
                                                                            100, digits = 1), gem.waarde = mean(waarde), gem.ratio = mean(dwratio))
}

# monsterFreq: onze kolom heette GWLichamen in plaats van grondwaterlichaam, verder niets aangepast

monsterFreq2 = function (x, param) 
{
  d <- x %>% filter(parameter == param) %>% group_by(GWLichamen, 
                                                     diepte) %>% count(putfilter) %>% group_by(GWLichamen, 
                                                                                               diepte, aantal.metingen = n) %>% summarise(aantal.putten = length(unique(putfilter))) %>% 
    spread(key = aantal.metingen, value = aantal.putten, 
           fill = 0)
  bereik <- 1:rev(names(d))[1]
  x <- bereik[!bereik %in% names(d)]
  d[, as.character(x)] <- 0
  d <- d %>% dplyr::select(GWLichamen, diepte, as.character(1:max(bereik)))
  return(d)
}

# toetsStatistiek: testSerie(d) eruit gehaald omdat deze foutmeldingen geeft (functie bestaat niet)

toetsStatistiek2 = function (d) 
{
  # testSerie(d)
  param <- d$parameter[1]
  nrm <- d$norm[1]
  d %>% mutate(dwratio = waarde/norm) %>% drop_na %>% summarise(ntot = n(), 
                                                                P50 = median(waarde), P95 = quantile(waarde, 0.95), perc.RG = round(nrow(d[d$detectielimiet > 
                                                                                                                                             0, ])/n() * 100, digits = 1), RG.min = min(waarde[detectielimiet > 
                                                                                                                                                                                                 0]), RG.max = max(waarde[detectielimiet > 0]), norm = nrm)
}

# trendAnalyse2: laatste else-statement stond op verkeerde plek, waardoor return(d.trend) errors gaf (d.trend bestaat niet)

trendAnalyse2 = function (d, n.reeks)
{
  if (n.reeks < 1) {
    return("totaal aantal reeksen onbekend om % trends te berekenen")
  }
  if (nrow(d) > 0) {
    i <- as.character(unique(d$putfilter))
    res2 <- lapply(i, FUN = mktrends, d) %>% do.call("rbind",
                                                     args = .) %>% na.omit()
    if (nrow(res2) > 0) {
      fdr <- res2 %>% select(p) %>% bhfdr()
      n.mk <- nrow(res2)
      d.trend1 <- res2 %>% filter(trend == "trend",
                                  p <= fdr$threshold) %>% mutate(trend = "trend- benoemd") %>%
        group_by(trend, direction) %>% summarise(n = n(),
                                                 percentage = paste(round(n()/n.reeks, digits = 2),
                                                                    round(n()/n.mk, digits = 2), sep = " / "),
                                                 gemiddeld.helling = mean((slope)), putfilters = paste(sort(unique(putfilter)),
                                                                                                       collapse = ", ")) %>% ungroup
      d.trend2 <- res2 %>% filter(trend == "trend",
                                  p <= fdr$threshold) %>% mutate(trend = "trend- benoemd") %>%
        group_by(trend) %>% summarise(n = n(), percentage = paste(round(n()/n.reeks,
                                                                        digits = 2), round(n()/n.mk, digits = 2), sep = " / "),
                                      gemiddeld.helling = mean((slope)), putfilters = paste(sort(unique(putfilter)),
                                                                                            collapse = ", ")) %>% ungroup
      d.trend3 <- res2 %>% filter(trend == "trend") %>%
        mutate(trend = "trend- niet benoemd") %>%
        group_by(trend) %>% summarise(n = n(), percentage = paste(round(n()/n.reeks,
                                                                        digits = 2), round(n()/n.mk, digits = 2), sep = " / "),
                                      gemiddeld.helling = mean((slope)), putfilters = paste(sort(unique(putfilter)),
                                                                                            collapse = ", ")) %>% ungroup
      d.trend <- bind_rows(d.trend1, d.trend2, d.trend3) %>%
        mutate(direction = ifelse(is.na(direction), "op/neer",
                                  direction)) %>% mutate(statistiek = paste(trend,
                                                                            direction)) %>% select(statistiek, n, percentage,
                                                                                                   gemiddeld.helling, putfilters)
    }else {
      d.trend <- NA
    }
  }
  
  return(d.trend)
}

# apply.Theil.Sen: om onbekende redenen konden we deze functie niet aanroepen (werd niet herkend), terwijl de functie wel in
# de package zit. Daarom los gedefinieerd, verder niets aangepast.

apply.Theil.Sen2 = function (y, Series) 
{
  aux.Series <- subset(Series, Jaar <= y)
  Theil.Sen <- mblm::mblm(waarde ~ Jaar, dataframe = aux.Series, 
                          repeated = FALSE)$coefficients
  slope.1 <- Theil.Sen[2]
  intercept.1 <- Theil.Sen[1]
  aux.Series <- transform(aux.Series, residual = NA)
  aux.Series$residual <- aux.Series$waarde - (intercept.1 + 
                                                slope.1 * aux.Series$Jaar)
  RSS.1 <- sum(aux.Series$residual^2)
  aux.Series <- subset(Series, Jaar >= y)
  Theil.Sen <- mblm::mblm(waarde ~ Jaar, dataframe = aux.Series, 
                          repeated = FALSE)$coefficients
  slope.2 <- Theil.Sen[2]
  intercept.2 <- Theil.Sen[1]
  aux.Series <- transform(aux.Series, residual = NA)
  aux.Series$residual <- aux.Series$waarde - (intercept.2 + 
                                                slope.2 * aux.Series$Jaar)
  RSS.2 <- sum(aux.Series$residual^2)
  RSS <- RSS.1 + RSS.2
  return(c(y, slope.1, slope.2, intercept.1, intercept.2, RSS))
}

# trendReversal: extra argument toegevoegd, waarin een tabel met de coëfficienten de output vormt. Verder toegevoegd dat
# de functie toont wanneer er te weinig jaren zijn voor trendbepaling.

trendReversal2 = function (i, x, trim = FALSE, rpDL = TRUE, trimfactor = 1.5, 
                           make.plot = FALSE, dw.plot = TRUE,wantCoefficients = F) 
{
  dw <- x$norm[1]
  param <- x$parameter[1]
  d <- x %>% filter(putfilter == i) %>% select(Jaar = meetjaar, 
                                               waarde = waarde, putfilter, detectielimiet, eenheid)
  if (trim) {
    d <- mutate(d, waarde = rmoutlier(d[["waarde"]], 
                                      factor = trimfactor, na.rm = TRUE))
  }
  series <- na.omit(d)
  if (rpDL) {
    d <- d %>% replaceDL()
  }
  min.no.years <- 5
  Years <- sort(unique(series$Jaar))
  output <- data.frame(turning.point = NA, slope.1 = NA, slope.2 = NA, 
                       intercept.1 = NA, intercept.2 = NA, p = 1, putfilter = i)
  p <- NA
  if (length(Years) >= min.no.years * 2) {
    permissible.range <- Years[(min.no.years):(length(Years) - 
                                                 min.no.years)]
    results.Theil.Sen <- as.data.frame(t(sapply(permissible.range, 
                                                apply.Theil.Sen2, series)))
    names(results.Theil.Sen) <- c("Jaar", "slope.1", 
                                  "slope.2", "intercept.1", "intercept.2", 
                                  "RSS")
    results.Theil.Sen <- transform(results.Theil.Sen, discordant.slopes = sign(slope.1 * 
                                                                                 slope.2))
    results.Theil.Sen
    best.Theil.Sen <- subset(results.Theil.Sen, discordant.slopes < 
                               0)
    minimum.RSS <- suppressWarnings(min(best.Theil.Sen$RSS))
    best.Theil.Sen <- subset(best.Theil.Sen, RSS <= minimum.RSS)[1, 
                                                                 ]
    rownames(best.Theil.Sen) <- NULL
    best.Theil.Sen
    turning.point <- as.numeric(best.Theil.Sen[1])
    quadratic.model <- lm(waarde ~ Jaar + I(Jaar^2), data = series)
    fitted.values <- fitted(quadratic.model)
    quadratic.model <- summary(quadratic.model)
    estimates.of.quadratic.model <- coef(quadratic.model)[, 
                                                          1]
    other.turning.point <- as.numeric(-0.5 * estimates.of.quadratic.model[2]/estimates.of.quadratic.model[3])
    P.value.reversal <- quadratic.model$coefficients[3, 4]
    range.of.years <- range(series$Jaar)
    if (any(results.Theil.Sen$discordant.slopes < 0) & other.turning.point >= 
        min(permissible.range) & other.turning.point <= max(permissible.range)) {
      
      if(wantCoefficients){
        table_coeff = data.frame(Name=i,Parameter = param, Type=c("Linear_1","Linear_2","Quadratic"),
                                 Intercept = c(best.Theil.Sen$intercept.1,best.Theil.Sen$intercept.2,estimates.of.quadratic.model[1]),
                                 Slope_1 = c(best.Theil.Sen$slope.1,best.Theil.Sen$slope.2,estimates.of.quadratic.model[2]),
                                 Slope_2 = c(NA,NA,estimates.of.quadratic.model[3]),TurningPoint = turning.point)
        output = table_coeff
      }else if (!make.plot) {
        output <- transform(best.Theil.Sen[1:5], p = P.value.reversal, 
                            putfilter = i)
        names(output)[1] <- "turning.point"
      }else {
        series <- series %>% mutate(detectielimiet = ifelse(detectielimiet == 
                                                              1, "< RG", "waarneming"))
        p <- ggplot(data = series, aes(x = Jaar, y = waarde, 
                                       colour = detectielimiet)) + geom_line(colour = "grey") + 
          geom_point()
        if (dw.plot) {
          p <- p + geom_hline(aes(yintercept = dw, linetype = "drempelwaarde"), 
                              colour = "red") + geom_hline(aes(yintercept = 0.75 * 
                                                                 dw, linetype = "75% drempelwaarde"), 
                                                           colour = "orange")
        }
        p <- p + geom_line(aes(x = Jaar, y = estimates.of.quadratic.model[1] + 
                                 estimates.of.quadratic.model[2] * series$Jaar + 
                                 estimates.of.quadratic.model[3] * (series$Jaar^2)), 
                           color = "black") + theme(legend.position = "none", 
                                                    axis.text.x = element_text(angle = 90, hjust = 1)) + 
          scale_x_continuous(breaks = series$Jaar, labels = series$Jaar) + 
          labs(x = "Jaar", y = paste("Concentratie", 
                                     param, strsplit(x$eenheid[1], " ")[[1]][1]), 
               title = paste("Trendomkering in filter ", 
                             i)) + theme(plot.title = element_text(hjust = 0.5), 
                                         legend.position = "bottom")
        aux.x.axis <- series$Jaar[series$Jaar <= turning.point]
        aux.y.axis <- best.Theil.Sen$intercept.1 + best.Theil.Sen$slope.1 * 
          aux.x.axis
        d <- data.frame(x = aux.x.axis, y = aux.y.axis)
        p <- p + geom_line(aes(x, y), data = d, color = ifelse(best.Theil.Sen$slope.1 < 
                                                                 0, "blue", "red"))
        aux.x.axis <- series$Jaar[series$Jaar >= turning.point]
        aux.y.axis <- best.Theil.Sen$intercept.2 + best.Theil.Sen$slope.2 * 
          aux.x.axis
        d <- data.frame(x = aux.x.axis, y = aux.y.axis)
        p <- p + geom_line(aes(x, y), data = d, color = ifelse(best.Theil.Sen$slope.2 < 
                                                                 0, "blue", "red"))
        p <- p + geom_vline(aes(xintercept = turning.point), 
                            color = "grey")
        p <- p + scale_color_manual(name = "", 
                                    values = c(`< RG` = "red", waarneming = "black"))
        p <- p + scale_linetype_manual(name = "", 
                                       values = c(2, 2), guide = guide_legend(override.aes = list(color = c("orange", 
                                                                                                            "red"))))
        output <- p
      }
    }else{
      if(wantCoefficients){
        table_coeff = data.frame(Name=i,Parameter = param, Type=c("Geen trend"),
                                 Intercept = NA,
                                 Slope_1 = NA,
                                 Slope_2 = NA,TurningPoint = NA)
        output = table_coeff
      }
    }
  }else{
    output = "Te weinig jaren voor trendbepaling"
  }
  return(output)
}`

**Comment by jspijker** [comment]
Aanpassingen zijn door @Lisetteavis doorgevoerd in repo.
